<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCAKKDF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCAKKDF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCAKKDF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCAKKDF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXCAKKDF\App_KernelDevDebugContainer([
    'container.build_hash' => 'XCAKKDF',
    'container.build_id' => 'ab7f5781',
    'container.build_time' => 1626648794,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCAKKDF');
